apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-gallery-data
  labels:
    app: video-gallery
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi